test-site/testsite/main/urls.py
from django.urls import path
from .views import *
from django.conf.urls import include


urlpatterns = [
    path('', index, name = 'home'),
]

test-site/testsite/products/urls.py
from django.urls import path
from .views import *


app_name = 'products'

urlpatterns = [
    path('', catalog, name = 'catalog'),
    path('<int:product_id>', lessons, name = 'lesson_list'),
    path('<int:product_id>/<int:lesson_id>', lesson_detail, name = 'lesson_detail'),
    path('video_moment/', video_moment, name='video_moment'),
]

test-site/testsite/testsite/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('', include('main.urls')),
    path('products/', include('products.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test-site/testsite/products/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import pytube



class BaseModel(models.Model):
    """Базовая абстрактная модель"""
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='дата обновления')

    class Meta:
        abstract = True


class Owner(BaseModel):
    """Модель владельцев продуктов"""
    name = models.CharField(max_length=255, unique=True,
                            verbose_name='имя')

    class Meta:
        verbose_name = 'владелец'
        verbose_name_plural = 'владельцы'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(BaseModel):
    """Модель продуктов"""
    title = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product', args=[self.slug])


class Lesson(BaseModel):
    """Модель уроков"""
    title = models.CharField(max_length=100, verbose_name='Название', )
    products = models.ManyToManyField(Product,related_name='related_lessons', verbose_name='Продукты в которых содержится')
    slug = models.SlugField(max_length=200, db_index=True)
    video = models.URLField(verbose_name='Ссылка на видео')
    duration = models.IntegerField(verbose_name='Длительность(сек)')


    class Meta:
        ordering = ('title',)
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.duration = pytube.YouTube(self.video).length
        if not self.slug:
            self.slug = slugify(self.title)
        super(Lesson, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('product:lesson', kwargs={'slug': self.slug})


class Access(models.Model):
    """Модель доступа"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='related_assigments')
    user = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='related_assigments')

    class Meta:
        unique_together = ('product', 'user')

    def str(self):
        if self.user:
            return f'Доступ пользователю {self.user.username} к продукту {self.product.name}'
        else:
            return 'Доступ без пользователя (например, админу)'
    def get_queryset(self):
        qs = super().get_querset()
        product_id = self.kwargs['pk']
        user_pk = self.request.user.pk
        try:
            Access.objects.get(product_id=product_id, user_id=user_pk)
        except Access.DoesNotExist:
            raise PermissionDenied
        return qs
    
    class Meta:
        verbose_name = 'Доступ'
        verbose_name_plural = 'Доступы'

test-site/testsite/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Lesson, Access
from backend.models import LessonViewing
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q


@login_required
def catalog(request):
    title = 'Продукты'
    access = Access.objects.filter(user=request.user).values('product__id')
    products = Product.objects.filter(Q(id__in=access))
    return render(request, 'products/catalog.html', {'title': title, 'products': products})


@login_required
def lessons(request, product_id):
    title = 'Уроки'
    access = Access.objects.filter(user=request.user).values('product__id')
    products = Product.objects.filter(id=product_id).filter(Q(id__in=access))
    
    for p in products:
        product_cat = p
    lessons = Lesson.objects.filter(products=product_cat)
    return render(request, 'products/lessons.html', {'title': title, 'products': products, 'lessons': lessons})


@login_required
def lesson_detail(request, product_id, lesson_id):
    title = 'Урок'
    access = Access.objects.filter(user=request.user).values('product__id')
    lesson = get_object_or_404(Lesson, id=lesson_id)
    product = Product.objects.filter(id=product_id).filter(Q(id__in=access))
    video_id = lesson.video[32:43:]
    Viewing, created = LessonViewing.objects.get_or_create(
        user=request.user, lesson=lesson)
    Viewing.save()
    return render(request, 'products/lesson_detail.html', {'title': title, 'product': product, 'lesson': lesson, 'video_id': video_id})



@csrf_exempt
def video_moment(request):
    if request.method == 'POST':
        moment = float(request.POST.get('moment'))
        lesson_id = request.POST.get('lesson_id')
        lesson = get_object_or_404(Lesson, id=lesson_id)
        Viewing, created = LessonViewing.objects.get_or_create(
        user=request.user, lesson=lesson)
        if Viewing.duration_viewed < moment:
            Viewing.duration_viewed = moment
            Viewing.save()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error'})

test-site/testsite/products/templates/products/catalog.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    ПРОДУКТЫ
{% endblock %}


{% block link %}
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'main/css/catalog.css' %}" >
{% endblock %}

{% block navbar %}
      <nav class="navbar">
         <button><a href="{% url 'home'%}" >ГЛАВНАЯ</a></button>
         <button><a href="{% url 'products:catalog' %}" class="active">ПРОДУКТЫ</a></button>
         <button><a href="{% url 'login' %}" >ВХОД</a></button>
      </nav>
{% endblock %}

{% block body %}
    <section class="home">
        <div class="catalog-content">
            {% for p in products %}
                <a href="{% url 'products:lesson_list' p.id %}">
                    <div class="chapter">
                        <p>{{p.title}}</p>   
                    </div>
                </a>  
            {% endfor %}
        </div>
    </section>
{% endblock %}

test-site/testsite/products/templates/products/lesson_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    ПРОДУКТЫ
{% endblock %}


{% block link %}
    <link rel="stylesheet" href="{% static 'main/css/catalog.css' %}" >
    <link rel="stylesheet" href="{% static 'main/css/detail.css' %}" >
{% endblock %}

{% block navbar %}
      <nav class="navbar">
         <button><a href="{% url 'home'%}" >ГЛАВНАЯ</a></button>
         <button><a href="{% url 'products:catalog' %}" class="active">ПРОДУКТЫ</a></button>
         <button><a href="{% url 'login' %}" >ВХОД</a></button>
      </nav>
{% endblock %}

{% block body %}
<section class="home">
    <div class="content">
        <h3>{{lesson.title}}</h3>
        <div id="player"></div>
        <p>Длительность видео - {{lesson.duration}} (сек)</p>

    </div>
</section>



<script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '360',
          width: '640',
          videoId: '{{ video_id }}',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setInterval(Update, 3000);
          done = true;
        }
      }
      function Current() {
        var number = player.getCurrentTime();
        return number
      }

      function Update() {
        $.ajax({
            type: 'POST',
            url: '{% url "products:video_moment" %}',
            data: {'moment': Current, 'lesson_id': {{lesson.id}} },
            success: function(response) {
                if (response.status === 'success') {
                    console.log('Момент видео успешно обработан на сервере');
                } else {
                    console.log('Ошибка при обработке момента видео на сервере');
                }
            },
            error: function(xhr) {
                console.log('Ошибка при отправке AJAX-запроса');
            }
        });
    }

    </script>

{% endblock %}

test-site/testsite/products/templates/products/lessons.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    ПРОДУКТЫ
{% endblock %}


{% block link %}
    
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'main/css/catalog.css' %}" >
{% endblock %}

{% block navbar %}
      <nav class="navbar">
         <button><a href="{% url 'home'%}" >ГЛАВНАЯ</a></button>
         <button><a href="{% url 'products:catalog' %}" class="active">ПРОДУКТЫ</a></button>
         <button><a href="{% url 'login' %}" >ВХОД</a></button>
      </nav>
{% endblock %}

{% block body %}
    <section class="home">
        <div class="catalog-content">
            {%for el in products%}     
                {% for p in lessons %}
                        <a href="{% url 'products:lesson_detail' el.id p.id %}">
                            <div class="chapter">
                                <p>{{p.title}}</p>
                            </div>
                        </a>       
                {% endfor %}
            {% endfor %}
        </div>
    </section>
{% endblock %}